In [4]:
import pandas as pd

# Constrituencies

In [23]:
data=pd.read_csv(r'csvs\Cleaned_constituency_data.csv')

In [24]:
df=data.copy()

In [25]:
df

,Year,Title,Extracted_Text,Region/Authority,Constituency
0,2024,"IMFC Statement by Christine Lagarde, President...",\r\n \r\n INTERNATIONAL MONETARY AND FINANCIA...,European Central Bank,OBS
1,2024,"IMFC Statement by HE Haitham Al Ghais, Secreta...",\r\n \r\n INTERNATIONAL MONETARY AND FINANCIA...,Organization of the Petroleum Exporting Countries,OBS
2,2024,"IMFC Statement by Ayman Al-Sayari, Governor of...",\r\n \r\n INTERNATIONAL MONETARY AND FINANCIA...,Saudi Arabia,SA
3,2024,"IMFC Statement by Antoine Armand, Minister of ...",INTERNATIONAL MONETARY AND FINANCIAL COMMITTE...,France,FF
4,2024,"IMFC Statement by Luis Caputo, Minister of Eco...",\r\n \r\n INTERNATIONAL MONETARY AND FINANCIA...,Argentina,AG
...,...,...,...,...,...
559,2004,IMFC Statement by the Honorable Domenico Sinis...,\r\n International Monetary and \r\nFinancial...,Italy,IT
560,2004,"IMFC Statement by the Honorable John W. Snow, ...",\r\n International Monetary and \r\nFinancial...,United States,US
561,2004,IMFC Statement by H.E. Sadakazu Tanigaki Minis...,\r\n International Monetary and \r\nFinancial...,Japan,JA
562,2004,"IMFC Statement By James D. Wolfensohn, Preside...",\r\n International Monetary and \r\nFinancial...,World Bank,OBS
563,2004,"Statement by Minister Gerrit Zalm, in his capa...",\r\n International Monetary and \r\nFinancial...,European Union,OBS

In [26]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

# Initialize the sentiment analyzer
analyzer = SentimentIntensityAnalyzer()

# Apply sentiment analysis
df['vader_scores'] = df['Extracted_Text'].apply(lambda x: analyzer.polarity_scores(str(x)))
df['vader_compound'] = df['vader_scores'].apply(lambda score_dict: score_dict['compound'])
df['vader_pos'] = df['vader_scores'].apply(lambda score_dict: score_dict['pos'])
df['vader_neu'] = df['vader_scores'].apply(lambda score_dict: score_dict['neu'])
df['vader_neg'] = df['vader_scores'].apply(lambda score_dict: score_dict['neg'])

In [27]:
sentiment_over_time = df.groupby('Year')['vader_compound'].mean().reset_index()

In [28]:
import plotly.express as px

fig = px.line(sentiment_over_time, x='Year', y='vader_compound',
              title='Average Sentiment Over Time (VADER)',
              labels={'vader_compound': 'Compound Sentiment Score'})
fig.show()

In [31]:
df = df[df['Constituency'] != "OBS"]

In [32]:
fig = px.box(df, x='Region/Authority', y='vader_compound',
             title='Sentiment Distribution by Authority',
             labels={'vader_compound': 'Compound Sentiment Score'})
fig.update_layout(xaxis_tickangle=-45)
fig.show()

# Communiques

In [12]:
data2=pd.read_csv(r'csvs\processed_data.csv')

In [15]:
df=data2.copy()

In [16]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

# Initialize the sentiment analyzer
analyzer = SentimentIntensityAnalyzer()

# Apply sentiment analysis
df['vader_scores'] = df['Extracted_Text'].apply(lambda x: analyzer.polarity_scores(str(x)))
df['vader_compound'] = df['vader_scores'].apply(lambda score_dict: score_dict['compound'])
df['vader_pos'] = df['vader_scores'].apply(lambda score_dict: score_dict['pos'])
df['vader_neu'] = df['vader_scores'].apply(lambda score_dict: score_dict['neu'])
df['vader_neg'] = df['vader_scores'].apply(lambda score_dict: score_dict['neg'])

In [17]:
sentiment_over_time = df.groupby('Year')['vader_compound'].mean().reset_index()

In [18]:
import plotly.express as px

fig = px.line(sentiment_over_time, x='Year', y='vader_compound',
              title='Average Sentiment Over Time (VADER)',
              labels={'vader_compound': 'Compound Sentiment Score'})
fig.show()

In [22]:
df

,Year,Title,Link,File_Path,Extracted_Text,vader_scores,vader_compound,vader_pos,vader_neu,vader_neg
0,2024,"IMFC Statement by Christine Lagarde, President...",https://meetings.imf.org/-/media/AMSM/Files/AM...,data\2024\IMFC Statement by Christine Lagarde_...,\r\n \r\n INTERNATIONAL MONETARY AND FINANCIA...,"{'neg': 0.091, 'neu': 0.784, 'pos': 0.125, 'co...",0.9979,0.125,0.784,0.091
1,2024,"IMFC Statement by HE Haitham Al Ghais, Secreta...",https://meetings.imf.org/-/media/AMSM/Files/AM...,data\2024\IMFC Statement by HE Haitham Al Ghai...,\r\n \r\n INTERNATIONAL MONETARY AND FINANCIA...,"{'neg': 0.047, 'neu': 0.853, 'pos': 0.1, 'comp...",0.9953,0.100,0.853,0.047
2,2024,"IMFC Statement by Ayman Al-Sayari, Governor of...",https://meetings.imf.org/-/media/AMSM/Files/AM...,data\2024\IMFC Statement by Ayman Al-Sayari_ G...,\r\n \r\n INTERNATIONAL MONETARY AND FINANCIA...,"{'neg': 0.079, 'neu': 0.751, 'pos': 0.171, 'co...",0.9995,0.171,0.751,0.079
3,2024,"IMFC Statement by Antoine Armand, Minister of ...",https://meetings.imf.org/-/media/AMSM/Files/AM...,data\2024\IMFC Statement by Antoine Armand_ Mi...,INTERNATIONAL MONETARY AND FINANCIAL COMMITTE...,"{'neg': 0.066, 'neu': 0.742, 'pos': 0.192, 'co...",0.9997,0.192,0.742,0.066
4,2024,"IMFC Statement by Luis Caputo, Minister of Eco...",https://meetings.imf.org/-/media/AMSM/Files/AM...,data\2024\IMFC Statement by Luis Caputo_ Minis...,\r\n \r\n INTERNATIONAL MONETARY AND FINANCIA...,"{'neg': 0.057, 'neu': 0.795, 'pos': 0.148, 'co...",1.0000,0.148,0.795,0.057
...,...,...,...,...,...,...,...,...,...,...
559,2004,IMFC Statement by the Honorable Domenico Sinis...,https://www.imf.org/External/AM/2004/imfc/stat...,data\2004\IMFC Statement by the Honorable Dome...,\r\n International Monetary and \r\nFinancial...,"{'neg': 0.062, 'neu': 0.796, 'pos': 0.142, 'co...",0.9999,0.142,0.796,0.062
560,2004,"IMFC Statement by the Honorable John W. Snow, ...",https://www.imf.org/External/AM/2004/imfc/stat...,data\2004\IMFC Statement by the Honorable John...,\r\n International Monetary and \r\nFinancial...,"{'neg': 0.057, 'neu': 0.734, 'pos': 0.209, 'co...",0.9998,0.209,0.734,0.057
561,2004,IMFC Statement by H.E. Sadakazu Tanigaki Minis...,https://www.imf.org/External/AM/2004/imfc/stat...,data\2004\IMFC Statement by H_E_ Sadakazu Tani...,\r\n International Monetary and \r\nFinancial...,"{'neg': 0.054, 'neu': 0.815, 'pos': 0.13, 'com...",0.9991,0.130,0.815,0.054
562,2004,"IMFC Statement By James D. Wolfensohn, Preside...",https://www.imf.org/External/AM/2004/imfc/stat...,data\2004\IMFC Statement By James D_ Wolfensoh...,\r\n International Monetary and \r\nFinancial...,"{'neg': 0.043, 'neu': 0.751, 'pos': 0.206, 'co...",0.9999,0.206,0.751,0.043
563,2004,"Statement by Minister Gerrit Zalm, in his capa...",https://www.imf.org/External/AM/2004/imfc/stat...,data\2004\Statement by Minister Gerrit Zalm_ i...,\r\n International Monetary and \r\nFinancial...,"{'neg': 0.064, 'neu': 0.775, 'pos': 0.161, 'co...",0.9999,0.161,0.775,0.064

In [21]:
fig = px.box(df, x='Region/Authority', y='vader_compound',
             title='Sentiment Distribution by Authority',
             labels={'vader_compound': 'Compound Sentiment Score'})
fig.update_layout(xaxis_tickangle=-45)
fig.show()

ValueError: Value of 'x' is not the name of a column in 'data_frame'. Expected one of ['Year', 'Title', 'Link', 'File_Path', 'Extracted_Text', 'vader_scores', 'vader_compound', 'vader_pos', 'vader_neu', 'vader_neg'] but received: Region/Authority